name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libncurses6 libstdc++6 zlib1g zlib1g-dev libffi-dev libssl-dev unzip openjdk-17-jdk
        python -m pip install --upgrade pip
        pip install cython buildozer
        
    - name: Accept Android Licenses
      run: |
            yes | $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses

    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.android
        echo "### Accepted licenses" > ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true

    - name: Force build-tools version in buildozer.spec
      run: |
        if grep -q "^# *android.build_tools" buildozer.spec; then
          sed -i '/^# *android.build_tools/s/^# *//' buildozer.spec
        fi
        sed -i 's/^android.build_tools =.*/android.build_tools = 34.0.0/' buildozer.spec || echo "android.build_tools = 34.0.0" >> buildozer.spec

    - name: Build the APK
      run: buildozer android debug

    - name: Upload the APK
      uses: actions/upload-artifact@v4
      with:
        name: MyKivyApp-APK
        path: bin/*.apk
