name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libncurses6 libstdc++6 zlib1g zlib1g-dev libffi-dev libssl-dev
        python -m pip install --upgrade pip
        pip install cython buildozer

    - name: Pre-accept Android SDK licenses
      run: |
        mkdir -p ~/.android
        echo '8933bad161af4178b1185d1a37fbf41ea5269c55' > ~/.android/repositories.cfg || true
        yes | sdkmanager --licenses || true

    - name: Patch buildozer.spec with stable build-tools version
      run: |
        sed -i '/^# android.build_tools/s/^# //' buildozer.spec
        sed -i '/^android.build_tools/ s/=.*/= 34.0.0/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyKivyApp-APK
        path: bin/*.apk
